[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
actix-rt = "2.8.0"
sqlx = { version = "0.6", default-features = false, features = ["migrate", "macros", "sqlite", "postgres", "runtime-actix-native-tls", "offline", "uuid", "chrono", "json"] } 
serde = "1.0"
anyhow = "1.0"
dotenv = "0.15.0"
env_logger = "0.10.0"
serde_json = "1.0"
async-graphql = { version = "5.0.7", features = ["chrono", "uuid"] }
async-graphql-actix-web = "5.0.7"
chrono = { version = "0.4.24", features = ["serde"] }
uuid = { version = "1.3.1", features = ["serde", "v4"] }