name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Docker Compose Plugin
              run: |
                  sudo apt-get update
                  sudo apt-get install -y docker-compose

            - name: Start PostgreSQL via Docker Compose
              working-directory: ./server
              run: docker-compose up -d

            - name: Install SQLx CLI
              run: |
                  cargo install --version=0.8.3 sqlx-cli --no-default-features --features postgres

            - name: Create .env file
              working-directory: ./server
              run: |
                  echo "HOST=127.0.0.1" >> .env
                  echo "PORT=8000" >> .env
                  echo "RUST_LOG=info,actix=debug" >> .env
                  echo "DATABASE_URL="postgres://postgres:postgres@localhost:5442/hood-test" >> .env
                  echo "SECRET="my_secret_key" >> .env
                  cat .env

            - name: Populate DB and Create Pool
              working-directory: ./server
              run: |
                  sqlx database create
                  sqlx migrate run

            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true

            - name: Build project
              working-directory: ./server
              run: cargo build --verbose

            - name: Run tests sequentially
              working-directory: ./server
              run: cargo test -- --test-threads=1
